
workstationtests:
  stage: test
  only: 
    - master
    - workstation
  script:
    - source $HOME/miniconda3/bin/activate
    - tox
    
clustertests:
    stage: test
    only:
     - slurm
     - master
     script:
     - source $HOME/miniconda3/bin/activate
     - pip install --upgrade pip
     - pip install --upgrade tox
     - tox

