stages:
    - tox
    - slurm
    - upload
    - deploy

variables:
    TEST_DIR: "$CI_PROJECT_DIR/syncopy/tests"

intellinux:
    stage: tox
    allow_failure: true
    tags:
    - deploy
    only:
    - master
    - dev
    variables:
        PYTEST_ADDOPTS: "--color=yes --tb=short --verbose"
        GIT_FETCH_EXTRA_FLAGS: --tags
        NO_SLURM: "true"
    script:
    - rm -rf ~/.spy
    - source $HOME/miniconda/etc/profile.d/conda.sh
    - conda clean --all -y
    - conda env update -f syncopy.yml --prune
    - conda activate syncopy
    - tox -p 0

powerlinux:
    stage: tox
    allow_failure: true
    tags:
    - power
    only:
    - master
    - dev
    variables:
        PYTEST_ADDOPTS: "--color=yes --tb=short --verbose"
        GIT_FETCH_EXTRA_FLAGS: --tags
    script:
    - rm -rf ~/.spy
    - source /opt/conda/etc/profile.d/conda.sh
    - conda clean --all -y
    - conda env update -f syncopy.yml --prune
    - conda activate syncopy
    - tox -p 0

intelwin:
    stage: tox
    allow_failure: true
    tags:
    - windows10
    only:
    - master
    - dev
    variables:
        PYTEST_ADDOPTS: "--color=yes --tb=short --verbose"
        GIT_FETCH_EXTRA_FLAGS: --tags
    script:
    - conda clean --all -y
    - conda env update -f syncopy.yml --prune
    - conda.bat activate syncopy
    - tox

m1macos:
    stage: tox
    allow_failure: true
    tags:
    - macos
    only:
    - master
    - dev
    variables:
        PYTEST_ADDOPTS: "--color=yes --tb=short --verbose"
        GIT_FETCH_EXTRA_FLAGS: --tags
    script:
    - ulimit -n 25000
    - rm -rf ~/.spy
    - source /opt/conda/etc/profile.d/conda.sh
    - conda clean --all -y
    - conda env update -f syncopy.yml --prune
    - conda activate syncopy
    - tox -p 0

slurmtest:
    stage: slurm
    allow_failure: true
    tags:
    - slurm
    only:
    - master
    - dev
    variables:
        PYTEST_ADDOPTS: "--color=yes --tb=short --verbose"
        GIT_FETCH_EXTRA_FLAGS: --tags
    script:
    - source /opt/conda/etc/profile.d/conda.sh
    - conda env update -f syncopy.yml --prune
    - conda activate syncopy
    - export PYTHONPATH=$CI_PROJECT_DIR
    - cd $TEST_DIR
    - srun -p DEV --mem=8000m -c 4 pytest --full test_specest.py -k 'not para'
    - srun -p DEV --mem=8000m -c 4 pytest --full test_specest.py -k 'para'
    - srun -p DEV --mem=8000m -c 4 pytest --full test_connectivity.py
    - srun -p DEV --mem=8000m -c 4 pytest --full --ignore=test_specest.py --ignore=test_connectivity.py
    
pypitest-poetry:
    stage: upload
    only:
    - 318-migrate-build-system-to-poetry
    tags:
    - deploy
    variables:
        GIT_FETCH_EXTRA_FLAGS: --tags
    script:
    - rm -rf dist/
    - source $HOME/miniconda/etc/profile.d/conda.sh
    # get poetry with python 3.8
    - conda activate spy38
    - poetry build
    # needs config pypi credentials on runner
    - poetry publish -r testpypi
    - sleep 300
    - conda create --yes --name piptest python=3.8
    - conda activate piptest
    - conda install --yes pip
    - version=$(grep 'version =' pyproject.toml | awk -F "\"" '{print $2}')
    - pip --no-cache-dir install --extra-index-url https://test.pypi.org/simple esi-syncopy==$version
    - python -c "import syncopy as spy"
    - conda deactivate
    - conda remove --yes --name piptest --all

pypitest:
    stage: upload
    only:
    - master
    - tags
    tags:
    - deploy
    variables:
        GIT_FETCH_EXTRA_FLAGS: --tags
    script:
    - source $HOME/miniconda/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda clean --all -y
    - conda env update -f syncopy.yml --prune
    - conda activate syncopy
    - conda install --yes twine keyring rfc3986
    - conda update --yes twine keyring rfc3986
    - rm -rf dist/ build/ esi_syncopy.egg-info/
    - python setup.py sdist bdist_wheel
    - tarname="$(basename -- $(ls dist/*.tar.gz) .tar.gz)"
    - version=$(sed -e 's/esi-syncopy-\(.*\)/\1/' <<< "$tarname")
    - twine upload --repository testpypi --config-file=~/.esipypirc dist/*
    - sleep 300
    - conda create --yes --name piptest python=3.8
    - conda activate piptest
    - conda install --yes pip
    - pip --no-cache-dir install --extra-index-url https://test.pypi.org/simple esi-syncopy==$version
    - python -c "import syncopy as spy"
    - conda deactivate
    - conda remove --yes --name piptest --all

pypideploy:
    stage: deploy
    when: manual
    only:
    - tags
    tags:
    - deploy
    variables:
        GIT_FETCH_EXTRA_FLAGS: --tags
    script:
    - source $HOME/miniconda/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda clean --all -y
    - conda env update -f syncopy.yml --prune
    - conda activate syncopy
    - conda install --yes twine keyring rfc3986
    - conda update --yes twine keyring rfc3986
    - rm -rf dist/ build/ esi_syncopy.egg-info/
    - python setup.py sdist bdist_wheel
    - twine upload --config-file=~/.esipypirc dist/*
