clusterTests:
    stage: test
    tags: 
    - slurm
    only:
    - master
    script:
    - source $HOME/miniconda3/bin/activate
    - pip install --upgrade pip
    - pip install --upgrade tox
    - srun -p 8GBS -c 4 tox --parallel 4

windowsTests:
    stage: test
    tags: 
    - windows10
    only:
    - master
    script:
    - pip install --upgrade --user pip
    - pip install --upgrade --user tox
    - tox


