stages:
    - test
    - deploy

clusterTests:
    stage: test
    tags: 
    - slurm
    only:
    - master
    - dev
    variables:
        PYTEST_ADDOPTS: "--color=yes --tb=short --verbose"
    script:
    - source $HOME/miniconda3/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda env update -f syncopy.yml --prune
    - conda activate syncopy
    - srun -p DEV --mem=8000m -c 4 tox -r 

windowsTests:
    stage: test
    allow_failure: true
    tags: 
    - windows10
    only:
    - master
    - dev
    variables:
        PYTEST_ADDOPTS: "--color=yes --tb=short --verbose"
    script:
    - python -m pip install --upgrade --user pip
    - python -m pip install --upgrade --user tox
    - tox -r

deploy-to-testpypi:
    stage: deploy
    only:
    - master
    - tags    
    tags:
    - deploy
    script: 
    - source $HOME/miniconda/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda env update -f syncopy.yml --prune
    - conda activate syncopy
    - conda install --yes twine keyring rfc3986
    - conda update --yes twine keyring rfc3986
    - python setup.py sdist bdist_wheel
    - tarname="$(basename -- $(ls dist/*.tar.gz) .tar.gz)"
    - version=$(sed -e 's/esi-syncopy-\(.*\)/\1/' <<< "$tarname")
    - whlfile="$(basename dist/*.whl)"
    - whltype=${whlfile##*$version}
    - whlname=${whlfile%%$version*}
    - rhash=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
    - mv dist/$tarname.tar.gz dist/$tarname$rhash.tar.gz
    - mv dist/$whlfile dist/$whlname$version$rhash$whltype
    - twine upload --repository testpypi dist/*
    - conda create --yes --name piptest
    - conda activate piptest
    - conda install --yes pip
    - pip --no-cache-dir install --extra-index-url https://testpypi.python.org/pypi esi-syncopy==$version
    - python -c "import syncopy as spy"
    - conda deactivate
    - conda remove --yes --name piptest --all

deploy-pypi:
    when: manual
    stage: deploy
    only:
    - master
    - tags    
    tags:
    - deploy
    script:
    - source $HOME/miniconda/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda env update -f syncopy.yml --prune
    - conda activate syncopy
    - conda install --yes twine keyring rfc3986
    - conda update --yes twine keyring rfc3986
    - python setup.py sdist bdist_wheel
    - twine upload --cert /etc/ssl/certs/ca-certificates.crt dist/*
    
docs:
    stage: deploy
    tags:
    - docs
    only:
    - dev
    - master
    - tags
    
    script:
    - if hash $HOME/miniconda/bin/conda 2>/dev/null; 
      then
         export PATH="$HOME/miniconda/bin:$PATH";
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda;
        export PATH="$HOME/miniconda/bin:$PATH";
      fi
    - source $HOME/miniconda/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda env update --file syncopy.yml
    - conda activate syncopy
    - cd doc
    - make html
    - rsync -av -e "ssh" --delete build/html/* root@monitor:/var/www/html/syncopy
