language: python
python:
  - "3.8"

cache: pip

# safelist
branches:
  only:
  - master
  - dev

install:
  - pip install "ruamel.yaml >=0.16,<0.17" setuptools_scm
  - python -m conda2pip
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python setup.py -q install
# command to run tests
script:
  - pytest -v
