name: SyNCoPy
channels:
  - defaults
 
dependencies:
  - python>= 3.7,<3.8
  - dask=1.0 
  - scipy >= 1.2, <1.4
  - numpy >= 1.15, <1.17
  - tqdm
  - h5py >= 2.9, < 3.0
  - pip
  - pip:
     - dask-jobqueue>= 0.4,<0.5

