channels:
  - defaults
  - conda-forge
 
dependencies:
  - numpy >= 1.15
  - scipy >= 1.5, < 1.6
  - matplotlib >= 3.3, < 3.5
  - tqdm >= 4.31
  - memory_profiler
  - dask >= 2.25
  - dask-jobqueue >= 0.7.1
  - h5py >= 2.9, < 3.0
  - bokeh
  - fsspec
