[tool.poetry]
name = "esi-syncopy-test"
packages = [
    {include = "syncopy"}
]
version = "2022.07"
license = "BSD-3-Clause"
description = "Syncopy is a Python toolkit for user-friendly large-scale electrophysiology data analysis. It is scalable to accomodate very large datasets and automatically makes use of available computing ressources. Syncopy is compatible with the Matlab toolbox FieldTrip."
authors = ["Stefan Fürtinger <sfuerti@esi-frankfurt.de>", "Tim Schäfer <tim.schaefer@esi-frankfurt.de>", "Gregor Mönke <gregor.moenke@esi-frankfurt.de>"]

[tool.poetry.dependencies]
python = "^3.8, <3.9"
h5py = ">=2.9"
numpy = ">=1.10"
scipy = ">= 1.5"
matplotlib = ">=3.5"
tqdm = ">=4.31"
natsort = "^8.1.0"
psutil = ""
fooof = ">= 1.0"
esi-acme = "2022.7"
ipdb = "^0.13.9"
memory-profiler = "^0.60.0"
numpydoc = "^1.4.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pytest = "^7.0"
ipython = "^8.0"
pytest-cov = "^3.0.0"
sphinx-bootstrap-theme = ""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
