name: Run Test under Mac OS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test-macos:
    runs-on: macos-latest
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        pip install poetry
    - name: Install SyNCoPy
      run: |
        poetry install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install optional dependency pynwb
      run: |
        poetry add pynwb
    - name: Test with pytest and get coverage
      run: |
        cd syncopy/tests
        # run parallel tests only for base CR
        poetry run pytest -k 'computationalroutine and parallel'
        # don't run general parallel tests
        poetry run pytest  -k 'not parallel'

